[package]
name = "solana-net-utils"
version = "1.8.14"
description = "Solana Network Utilities"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-net-utils"
edition = "2018"

[dependencies]
bincode = "1.3.1"
clap = "2.33.1"
log = "0.4.11"
nix = "0.20.0"
rand = "0.7.0"
serde = "1.0.122"
serde_derive = "1.0.103"
socket2 = "0.3.17"
solana-clap-utils = { git = "https://github.com/solindex/clap-utils.git", version = "=1.8.14" }
solana-logger = { git = "https://github.com/solindex/logger.git", version = "=1.8.14" }
solana-sdk = { git = "https://github.com/solindex/sdk.git", version = "=1.8.14" }
solana-version = { git = "https://github.com/solindex/version.git", version = "=1.8.14" }
tokio = { version = "1", features = ["full"] }
url = "2.1.1"

[lib]
name = "solana_net_utils"

[[bin]]
name = "solana-ip-address"
path = "src/bin/ip_address.rs"

[[bin]]
name = "solana-ip-address-server"
path = "src/bin/ip_address_server.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
